name: Symfony CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: Pilulier_Test
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U symfony"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      pillbox-simulator:
        image: piluleo_hardware_simulator:latest
        ports:
          - 5000:5000

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up PHP with necessary extensions
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, pdo, pdo_pgsql, curl, xml
          coverage: xdebug

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL to be ready
        run: |
          dockerize -wait tcp://localhost:5432 -timeout 60s

      # Create .env.test.local for the test environment
      - name: Setup .env.test.local
        run: |
          echo "APP_ENV=test" >> .env.test.local
          echo "APP_DEBUG=1" >> .env.test.local
          echo "APP_SECRET=0897c2d6e68504e2c1b49d52519081f5" >> .env.test.local
          echo "DATABASE_URL=pgsql://symfony:symfony_password@127.0.0.1:5432/Pilulier_Test" >> .env.test.local
          echo "PILULIER_API_BASE_URL=http://127.0.0.1:5000/pillbox" >> .env.test.local
          echo "PILULIER_REMOTE_URL=http://127.0.0.1:5000/pillbox/remote" >> .env.test.local
          echo "CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'" >> .env.test.local
          echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env.test.local

      # Cache Composer dependencies
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install Composer dependencies
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      # Migrate database schema
      - name: Run Doctrine Migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        env:
          DATABASE_URL: pgsql://symfony:symfony_password@127.0.0.1:5432/Pilulier_Test
          PILULIER_API_BASE_URL: http://127.0.0.1:5000/pillbox
          PILULIER_REMOTE_URL: http://127.0.0.1:5000/pillbox/remote
        run: ./vendor/bin/phpunit --testdox --coverage-text